### ISSUE TITLE
能否增加443端口伪装网站

### ISSUE THREAD

**Issue by BrunuhVille** [crossfw/Air-Universe#1]
使用443端口tls的节点，如果搭配没有伪装网站，特殊节日很容易被封锁
目前网上有一些教程 sni分流，nginx，v2ray trojan共存
如果能加进来就好了

**Comment by genics** [comment]
希望有对应的宝塔教程

**Comment by crossfw** [comment]
使用自定义入站配置可兼容任何单用户配置教程，请保留API端口即可

**Comment by Jerry-Zheng-bilibili** [comment]
> 

可以不使用443端口作为tls节点，如有需要使用443复用的话可以自行添加path的路径的
