### ISSUE TITLE
报错existing tag found: p0

### ISSUE THREAD

**Issue by erbai666** [crossfw/Air-Universe#11]
Error-正确配置后报错

Failed to add inbound - rpc error: code = Unknown desc = app/proxyman/inbound: existing tag found: p0"

`au配置：
{
  "panel": {
    "url": "https://www..xyz/",
    "key": "",
    "node_ids": [23]
  },
  "proxy": {
    "type":"xray",
    "log_path": "/var/log/au/xr.log", 
    "cert": {
      "cert_path": "/crt/cert.crt", 
      "key_path": "/crt/key.key"
    }
  }
}

xray配置：
{
  "log": {
    "access": "/var/log/au/xr.log"
  },
  "stats": {},
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "policy": {
    "levels": {
      "0": {
        "connIdle": 300,
        "downlinkOnly": 20,
        "handshake": 20,
        "uplinkOnly": 20,
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    }
  },
  "inboundDetour": [
    {
      "listen": "127.0.0.1",
      "port": 10085,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blackhole",
      "protocol": "blackhole",
      "settings": {}
    }
  ],
  "routing": {
    "settings": {
      "rules": [
        {
          "inboundTag": [
            "api"
          ],
          "outboundTag": "api",
          "type": "field"
        },
        {
          "type": "field",
          "ip": [
            "127.0.0.1/32",
            "10.0.0.0/8",
            "fc00::/7",
            "fe80::/10",
            "172.16.0.0/12"
          ],
          "protocol": [
            "bittorrent"
          ],
          "inboundTag": [
            "p0",
            "p1",
            "p2",
            "p3",
            "p4",
            "p5",
            "p6"
          ],
          "outboundTag": "blackhole"
        }
      ]
    },
    "strategy": "rules"
  }
}`

（要谢谢dalao的照顾了

**Comment by crossfw** [comment]
检查下xray日志，怀疑是air universe重复启动导致的

**Comment by LemonBlog** [comment]
一直重复

`2021/03/23 22:20:05 WARNING: proto: file "common/serial/typed_message.proto" is already registered
	previously from: "github.com/v2fly/v2ray-core/v4/common/serial"
	currently from:  "github.com/xtls/xray-core/common/serial"
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict `

**Comment by crossfw** [comment]
> 一直重复
> 
> `2021/03/23 22:20:05 WARNING: proto: file "common/serial/typed_message.proto" is already registered previously from: "github.com/v2fly/v2ray-core/v4/common/serial" currently from: "github.com/xtls/xray-core/common/serial" A future release will panic on registration conflicts. See: https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict `

不用管这些错误

**Comment by erbai666** [comment]
`2021/03/23 22:27:44 27.214.6.80:57645 accepted tcp:www.qualcomm.cn:80 [p0 >> direct] email: 1216-p0 `

**Comment by crossfw** [comment]
> `2021/03/23 22:27:44 27.214.6.80:57645 accepted tcp:www.qualcomm.cn:80 [p0 >> direct] email: 1216-p0 `

这是正常的，说明已经添加成功了
