### ISSUE TITLE
对接v2board失败

### ISSUE THREAD

**Issue by xieruan** [crossfw/Air-Universe#12]
Mar 24 20:20:38 vultr.guest au[6592]:         previously from: "github.com/v2fly/v2ray-core/v4/proxy/vmess/outbound"
Mar 24 20:20:38 vultr.guest au[6592]:         currently from:  "github.com/xtls/xray-core/proxy/vmess/outbound"
Mar 24 20:20:38 vultr.guest au[6592]: A future release will panic on registration conflicts. See:
Mar 24 20:20:38 vultr.guest au[6592]: https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
Mar 24 20:20:38 vultr.guest au[6592]: 2021/03/24 20:20:38 WARNING: proto: file "app/dispatcher/config.proto" is already registered
Mar 24 20:20:38 vultr.guest au[6592]:         previously from: "github.com/v2fly/v2ray-core/v4/app/dispatcher"
Mar 24 20:20:38 vultr.guest au[6592]:         currently from:  "github.com/xtls/xray-core/app/dispatcher"
Mar 24 20:20:38 vultr.guest au[6592]: A future release will panic on registration conflicts. See:
Mar 24 20:20:38 vultr.guest au[6592]: https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
Mar 24 20:20:38 vultr.guest au[6592]: time="2021-03-24T20:20:38+08:00" level=error msg="Failed to read config file - invalid character 'v' looking for b

**Comment by crossfw** [comment]
贴出你的Air-Universe config, 在今天下午修复了一个一键脚本的问题, 请隐藏敏感信息后贴出

**Comment by xieruan** [comment]
{
  "panel": {
    "type": "${panelType}",
    "url": "${pUrl}",
    "key": "${nKey}",
    "node_ids": [${nIds}],
    "nodes_type": [${nType}],
    "nodes_proxy_protocol": [${npp}]
  }
大佬，好像是你脚本的nodes_type里的类型没带“”，应该这样  "nodes_type": ["vmess", "ss"]。

文档里PanelObject格式是对的，脚本错了

**Comment by xieruan** [comment]
改后对接成功，但显示Mar 24 20:44:56 vultr.guest au[15221]: time="2021-03-24T20:44:56+08:00" level=warning msg="NodeID: 1 IDIndex 0 - Failed to post system load - unsupporte

**Comment by crossfw** [comment]
@xieruan 无影响，下版本会去除v2board提交系统状态

**Comment by xieruan** [comment]
> @xieruan 无影响，下版本会去除v2board提交系统状态

大佬，是这个新改动吗？
https://github.com/v2board/v2board/commit/cbe5882e0125aa2a77e0754ab5e7e0e33938f229

**Comment by crossfw** [comment]
@xieruan 2 hours 前提交的，近期应该不会适配。

**Comment by crossfw** [comment]
> {
> "panel": {
> "type": "${panelType}",
> "url": "${pUrl}",
> "key": "${nKey}",
> "node_ids": [${nIds}],
> "nodes_type": [${nType}],
> "nodes_proxy_protocol": [${npp}]
> }
> 大佬，好像是你脚本的nodes_type里的类型没带“”，应该这样 "nodes_type": ["vmess", "ss"]。
> 
> 文档里PanelObject格式是对的，脚本错了

部署时需要手动输入类似 "vmess","ss" 格式的字符串

**Comment by xieruan** [comment]
> > {
> > "panel": {
> > "type": "${panelType}",
> > "url": "${pUrl}",
> > "key": "${nKey}",
> > "node_ids": [${nIds}],
> > "nodes_type": [${nType}],
> > "nodes_proxy_protocol": [${npp}]
> > }
> > 大佬，好像是你脚本的nodes_type里的类型没带“”，应该这样 "nodes_type": ["vmess", "ss"]。
> > 文档里PanelObject格式是对的，脚本错了
> 
> 部署时需要手动输入类似 "vmess","ss" 格式的字符串

好的，多谢大佬。在对接v2board ws后，使用时显示v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://ip:10089/zxcdsdvntsswefghijmb): 302 Moved Temporarily > websocket: bad handshake v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://ip:10089/zxcdsdvntsswefghijmb):  > read tcp 192.168.31.244:1474->ip:10089: wsarecv: An existing connection was forcibly closed by the remote host.] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by xieruan** [comment]
> @xieruan 2 hours 前提交的，近期应该不会适配。

好的，多谢大佬

另外v2board对接成功后，使用时
2021/03/24 21:37:36 [Warning] [2664498624] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://ip:10089/zxcvntsswefghijmb): 400 Bad Request > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

> > > {
> > > "panel": {
> > > "type": "${panelType}",
> > > "url": "${pUrl}",
> > > "key": "${nKey}",
> > > "node_ids": [${nIds}],
> > > "nodes_type": [${nType}],
> > > "nodes_proxy_protocol": [${npp}]
> > > }
> > > 大佬，好像是你脚本的nodes_type里的类型没带“”，应该这样 "nodes_type": ["vmess", "ss"]。
> > > 文档里PanelObject格式是对的，脚本错了
> > 
> > 
> > 部署时需要手动输入类似 "vmess","ss" 格式的字符串
> 
> 好的，多谢大佬。在对接v2board ws后，使用时显示v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://ip:10089/zxcdsdvntsswefghijmb): 302 Moved Temporarily > websocket: bad handshake v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://ip:10089/zxcdsdvntsswefghijmb): > read tcp 192.168.31.244:1474->ip:10089: wsarecv: An existing connection was forcibly closed by the remote host.] > v2ray.com/core/common/retry: all retry attempts failed


v2board ws协议配置为{"path":"/zxcdsdvntsswefghijmb","headers":{"Host":"xxx.com"}}

**Comment by crossfw** [comment]
> > @xieruan 2 hours 前提交的，近期应该不会适配。
> 
> 好的，多谢大佬
> 
> 另外v2board对接成功后，使用时
> 2021/03/24 21:37:36 [Warning] [2664498624] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://ip:10089/zxcvntsswefghijmb): 400 Bad Request > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
> 
> > > > {
> > > > "panel": {
> > > > "type": "${panelType}",
> > > > "url": "${pUrl}",
> > > > "key": "${nKey}",
> > > > "node_ids": [${nIds}],
> > > > "nodes_type": [${nType}],
> > > > "nodes_proxy_protocol": [${npp}]
> > > > }
> > > > 大佬，好像是你脚本的nodes_type里的类型没带“”，应该这样 "nodes_type": ["vmess", "ss"]。
> > > > 文档里PanelObject格式是对的，脚本错了
> > > 
> > > 
> > > 部署时需要手动输入类似 "vmess","ss" 格式的字符串
> > 
> > 
> > 好的，多谢大佬。在对接v2board ws后，使用时显示v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://ip:10089/zxcdsdvntsswefghijmb): 302 Moved Temporarily > websocket: bad handshake v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://ip:10089/zxcdsdvntsswefghijmb): > read tcp 192.168.31.244:1474->ip:10089: wsarecv: An existing connection was forcibly closed by the remote host.] > v2ray.com/core/common/retry: all retry attempts failed
> 
> v2board ws协议配置为{"path":"/zxcdsdvntsswefghijmb","headers":{"Host":"xxx.com"}}

不太清楚具体发生了什么，如果可以正常上网的话应该没有问题。

**Comment by xieruan** [comment]
> > > @xieruan 2 hours 前提交的，近期应该不会适配。
> > 
> > 
> > 好的，多谢大佬
> > 另外v2board对接成功后，使用时
> > 2021/03/24 21:37:36 [Warning] [2664498624] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://ip:10089/zxcvntsswefghijmb): 400 Bad Request > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
> > > > > {
> > > > > "panel": {
> > > > > "type": "${panelType}",
> > > > > "url": "${pUrl}",
> > > > > "key": "${nKey}",
> > > > > "node_ids": [${nIds}],
> > > > > "nodes_type": [${nType}],
> > > > > "nodes_proxy_protocol": [${npp}]
> > > > > }
> > > > > 大佬，好像是你脚本的nodes_type里的类型没带“”，应该这样 "nodes_type": ["vmess", "ss"]。
> > > > > 文档里PanelObject格式是对的，脚本错了
> > > > 
> > > > 
> > > > 部署时需要手动输入类似 "vmess","ss" 格式的字符串
> > > 
> > > 
> > > 好的，多谢大佬。在对接v2board ws后，使用时显示v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://ip:10089/zxcdsdvntsswefghijmb): 302 Moved Temporarily > websocket: bad handshake v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://ip:10089/zxcdsdvntsswefghijmb): > read tcp 192.168.31.244:1474->ip:10089: wsarecv: An existing connection was forcibly closed by the remote host.] > v2ray.com/core/common/retry: all retry attempts failed
> > 
> > 
> > v2board ws协议配置为{"path":"/zxcdsdvntsswefghijmb","headers":{"Host":"xxx.com"}}
> 
> 不太清楚具体发生了什么，如果可以正常上网的话应该没有问题。

报这个错误不能正常上网，我确信ip和端口都是通的

**Comment by crossfw** [comment]
> > > > @xieruan 2 hours 前提交的，近期应该不会适配。
> > > 
> > > 
> > > 好的，多谢大佬
> > > 另外v2board对接成功后，使用时
> > > 2021/03/24 21:37:36 [Warning] [2664498624] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://ip:10089/zxcvntsswefghijmb): 400 Bad Request > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed
> > > > > > {
> > > > > > "panel": {
> > > > > > "type": "${panelType}",
> > > > > > "url": "${pUrl}",
> > > > > > "key": "${nKey}",
> > > > > > "node_ids": [${nIds}],
> > > > > > "nodes_type": [${nType}],
> > > > > > "nodes_proxy_protocol": [${npp}]
> > > > > > }
> > > > > > 大佬，好像是你脚本的nodes_type里的类型没带“”，应该这样 "nodes_type": ["vmess", "ss"]。
> > > > > > 文档里PanelObject格式是对的，脚本错了
> > > > > 
> > > > > 
> > > > > 部署时需要手动输入类似 "vmess","ss" 格式的字符串
> > > > 
> > > > 
> > > > 好的，多谢大佬。在对接v2board ws后，使用时显示v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://ip:10089/zxcdsdvntsswefghijmb): 302 Moved Temporarily > websocket: bad handshake v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://ip:10089/zxcdsdvntsswefghijmb): > read tcp 192.168.31.244:1474->ip:10089: wsarecv: An existing connection was forcibly closed by the remote host.] > v2ray.com/core/common/retry: all retry attempts failed
> > > 
> > > 
> > > v2board ws协议配置为{"path":"/zxcdsdvntsswefghijmb","headers":{"Host":"xxx.com"}}
> > 
> > 
> > 不太清楚具体发生了什么，如果可以正常上网的话应该没有问题。
> 
> 报这个错误不能正常上网，我确信ip和端口都是通的

我明天会尝试复现一下

**Comment by crossfw** [comment]
预计今天推送新版

**Comment by xieruan** [comment]
大佬，今天的新版本，vmes-ws可用，但vmess-tcp 能对接成功，用不了，ss也一样。

vmess-tcp日志
2021/03/26 20:50:34 [Warning] [2454540433] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp [ip]:10088: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed


ss日志
2021/03/26 20:49:58 [Warning] [3621948160] v2ray.com/core/proxy/http: failed to read response from ip:80 > io: read/write on closed pipe
2021/03/26 20:49:58 [Warning] [3001790744] v2ray.com/core/proxy/http: failed to read response from Ip:80 > io: read/write on closed pipe

**Comment by crossfw** [comment]
> 大佬，今天的新版本，vmes-ws可用，但vmess-tcp 能对接成功，用不了，ss也一样。
> 
> vmess-tcp日志
> 2021/03/26 20:50:34 [Warning] [2454540433] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp [ip]:10088: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
> 
> ss日志
> 2021/03/26 20:49:58 [Warning] [3621948160] v2ray.com/core/proxy/http: failed to read response from ip:80 > io: read/write on closed pipe
> 2021/03/26 20:49:58 [Warning] [3001790744] v2ray.com/core/proxy/http: failed to read response from Ip:80 > io: read/write on closed pipe
明天看下，可能考虑重构v2board对接逻辑

**Comment by crossfw** [comment]
> > 大佬，今天的新版本，vmes-ws可用，但vmess-tcp 能对接成功，用不了，ss也一样。
> > vmess-tcp日志
> > 2021/03/26 20:50:34 [Warning] [2454540433] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp [ip]:10088: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
> > ss日志
> > 2021/03/26 20:49:58 [Warning] [3621948160] v2ray.com/core/proxy/http: failed to read response from ip:80 > io: read/write on closed pipe
> > 2021/03/26 20:49:58 [Warning] [3001790744] v2ray.com/core/proxy/http: failed to read response from Ip:80 > io: read/write on closed pipe
> 
> 明天看下，可能考虑重构v2board对接逻辑

能不能发下你的v2board配置，注意到v2board可以自定义配置，所以增加了不确定性

**Comment by xieruan** [comment]
<img width="359" alt="2" src="https://user-images.githubusercontent.com/59883140/112647333-5dc53f80-8e83-11eb-95ba-eb4af70655d2.png">
<img width="369" alt="1" src="https://user-images.githubusercontent.com/59883140/112647355-63bb2080-8e83-11eb-9907-ff9814e08668.png">

**Comment by crossfw** [comment]
我会在明天处理，谢谢反馈

**Comment by xieruan** [comment]
> 我会在明天处理，谢谢反馈

应该是我多谢大佬的开发还有耐心处理issues

**Comment by crossfw** [comment]
测试下来没有问题，请问你是多节点还是单节点

**Comment by xieruan** [comment]
> 测试下来没有问题，请问你是多节点还是单节点

多节点

**Comment by xieruan** [comment]
> > 测试下来没有问题，请问你是多节点还是单节点
> 
> 多节点

我试试看单节点行不行

**Comment by xieruan** [comment]
> 测试下来没有问题，请问你是多节点还是单节点

大佬，还是一样的，我v2board用的https://github.com/v2board/v2board/releases/tag/1.5.0

<img width="557" alt="b6be4f74d9c14b95855cb1290dd1a80" src="https://user-images.githubusercontent.com/59883140/112713817-04f0b800-8f12-11eb-8ce3-0ec617f301e4.png">

**Comment by crossfw** [comment]
@xieruan 附上air-u的log

**Comment by xieruan** [comment]
> @xieruan 附上air-u的log

xray的log，au的好像没啥
2021/03/27 16:47:16 "ip" rejected  proxy/shadowsocks: failed to read IV > proxyproto: proxy protocol signature not present

**Comment by crossfw** [comment]
> > @xieruan 附上air-u的log
> 
> xray的log，au的好像没啥
> 2021/03/27 16:47:16 "ip" rejected proxy/shadowsocks: failed to read IV > proxyproto: proxy protocol signature not present

你设置了接收中转ip但没有走中转流量? 使用http中转的流量无须开启

**Comment by xieruan** [comment]
> > > @xieruan 附上air-u的log
> > 
> > 
> > xray的log，au的好像没啥
> > 2021/03/27 16:47:16 "ip" rejected proxy/shadowsocks: failed to read IV > proxyproto: proxy protocol signature not present
> 
> 你设置了接收中转ip但没有走中转流量? 使用http中转的流量无须开启

大佬，这个设置吗？nodes_proxy_protocol

**Comment by crossfw** [comment]
@xieruan 是的，默认为false就好

**Comment by xieruan** [comment]
> @xieruan 是的，默认为false就好

好的，多谢大佬
