### ISSUE TITLE
关于一键部署问题

### ISSUE THREAD

**Issue by ckbkdj** [crossfw/Air-Universe#13]
选择了 v2board 
/usr/local/bin/au: Text file busy
Failed to restart xray.service: Unit au.service has a bad unit file setting.
See system logs and 'systemctl status xray.service' for details.
Failed to start au.service: Unit au.service has a bad unit file setting.
See system logs and 'systemctl status au.service' for details.

**Comment by crossfw** [comment]
参考 https://blog.csdn.net/z191726501/article/details/78488295
文件名使用 au
