### ISSUE TITLE
关于使用最新一键脚本进行trojan对接ssp时疑似证书获取错误的问题

### ISSUE THREAD

**Issue by asd307769162** [crossfw/Air-Universe#19]
错误日志：time="2021-04-08T11:15:56+08:00" level=info msg="NodeID: 11 IDIndex 0 - Node info changed "
time="2021-04-08T11:15:56+08:00" level=warning msg="NodeID: 11 IDIndex 0 - Failed to remove inbound - rpc error: code = Unknown desc = not enough information for making a decision"
time="2021-04-08T11:15:56+08:00" level=warning msg="NodeID: 11 IDIndex 0 - Failed to add inbound - infra/conf: failed to parse key > open /root/.acme.sh/1.5thunter.tk_ecc/1.5thunter.tk.key : no such file or directory"
具体描述：防火墙已关闭，证书已赋予权限。路径没问题。请问如何处理

**Comment by crossfw** [comment]
明天尝试复现下
