### ISSUE TITLE
不支持 Xray v1.5.1

### ISSUE THREAD

**Issue by tearfulDalvik** [crossfw/Air-Universe#2]
如题，https://github.com/XTLS/Xray-core/releases/tag/v1.5.1

如果使用了 v1.5.1 的 Xray，不会显示任何错误，但是 inbound 端口没有被监听

**Comment by crossfw** [comment]
将在成为正式版本后维护，目前使用一键脚本任安装 v1.5.0

**Comment by jinwyp** [comment]
现在你的官方脚本安装后 安装的已经是1.5.2的xray了 导致无法运行

https://github.com/XTLS/Xray-core/releases/tag/v1.5.2  已经发布了
