### ISSUE TITLE
回传记录到v2b服务器时错误     

### ISSUE THREAD

**Issue by ovenone** [crossfw/Air-Universe#21]
![image](https://user-images.githubusercontent.com/6820936/115830290-a9e3af80-a442-11eb-8a70-2428ae34c160.png)

{
  "panel": {
    "type": "v2board",
    "url": "http://u*****a.com",
    "key": "ac6P*****cW",
    "node_ids": [1],
    "nodes_type": ["vmess"]
  },
  "proxy": {
    "type":"xray"
  }
}

v2b面板版本1.5.0

**Comment by crossfw** [comment]
1. 确认目前xray没有退出, 即用户还可以使用服务.
2. 调整日志等级到debug.

查看了 v2board代码 没有发现相关改动, 目前情况无法判断
