### ISSUE TITLE
面板支持

### ISSUE THREAD

**Issue by gouidea** [crossfw/Air-Universe#25]
大大，au往后会支持 sspanel Metron 嘛

**Comment by crossfw** [comment]
我觉得API是通用的

**Comment by gouidea** [comment]
实际使用情况，uim 和 metron 不一样，uim确实可以轻松无脑对接，metron对接不上au，XrayR也是这样的，XrayR和au应该是同一种类型，都是这种情况
metron使用soga和波塞冬以及rico之类的后端都是可以的
我是用过metron，测试对比过，才敢这么提
大大有空研究研究

**Comment by crossfw** [comment]
目前看来没有兼容性问题，请提交日志以确认问题

**Comment by gouidea** [comment]
May 16 19:07:09 10-7-183-250 systemd[1]: Started Air-Universe - main Service.
May 16 19:07:09 10-7-183-250 au[19307]: time="2021-05-16T19:07:09+08:00" level=warning msg="InTags length isn't equal to nodeID length, adding inTags"
May 16 19:07:11 10-7-183-250 au[19307]: time="2021-05-16T19:07:11+08:00" level=info msg="NodeID: 60 IDIndex 0 - Successfully start sync thread"
May 16 19:07:14 10-7-183-250 au[19307]: time="2021-05-16T19:07:14+08:00" level=info msg="NodeID: 60 IDIndex 0 - Successfully add inbound"
May 16 19:07:14 10-7-183-250 au[19307]: time="2021-05-16T19:07:14+08:00" level=warning msg="NodeID: 60 IDIndex 0 - Failed to add users - rpc error: code = Unknown desc = app/proxyman/command: failed to parse user > proxy/vmess: failed to parse ID > invalid UUID: "

--- 
面板上显示的都是正常的状态，包括负载情况，都可以看到，就是这里解析不了识别码，但是soga就无此异常记录

**Comment by crossfw** [comment]
请问面板多少用户，如果是测试用途的话请多加几个有效用户测试，并反馈使用其他后端时，这些用户是否可以正常连接的情况。此情况为用户的uuid没有被前端面板生成所致。

**Comment by gouidea** [comment]
条件具备，就很奇怪，就是这里，其他后端可以对接上，au和XrayR就会有这个出现

已经放弃metron，转投uim了，感谢大大回复，大大加油，期待好作品
