### ISSUE TITLE
wiki里面默认证书的路径写错了

### ISSUE THREAD

**Issue by jinwyp** [crossfw/Air-Universe#29]
https://github.com/crossfw/Air-Universe/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

TLS 所需的证书，默认路径 /usr/local/share/server.crt 与 /usr/local/share/server.key，仅在启用TLS时需要

应该为
TLS 所需的证书，默认路径 /usr/local/share/au/server.crt 与 /usr/local/share/au/server.key，仅在启用TLS时需要

虽然安装脚本里面是对的, 但这个错误说明也非常坑人.

**Comment by crossfw** [comment]
感谢指出，现已更正

**Comment by alexallen1** [comment]
一个小小建议
反代跑trojan，我阅读`https://github.com/crossfw/Air-Universe/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6`
参考最底部的完整的配置
运行发现不行。
最后手动添加上 "cert": {
则运行成功。
建议提示一下反代一定要"cert": {

**Comment by heaid** [comment]
> 一个小小建议
> 反代跑trojan，我阅读`https://github.com/crossfw/Air-Universe/wiki/配置文件`
> 参考最底部的完整的配置
> 加个"force_close_tls": true （客户端也跳过证书验证）
> 运行发现不行。
> 最后手动添加上 "cert": {两个证书路径
> 则运行成功。
> 建议提示一下反代一定要"cert": {

  "proxy": {
    "type":"xray",
    "force_close_tls": true,
      "cert": {
    "cert_path": "/etc/XrayR/cert/certificates/ceshi.abc.cyou.crt",
    "key_path": "/etc/XrayR/cert/certificates/ceshi.abc.cyou.key"
  }
  }
}


 用Nginx反代trojan。我今天也测试了下 ，你的意思是这样吗，不过我这样也不行诶 奇怪。

**Comment by heaid** [comment]
ky 

> 一个小小建议
> 反代跑trojan，我阅读`https://github.com/crossfw/Air-Universe/wiki/配置文件`
> 参考最底部的完整的配置
> 加个"force_close_tls": true （客户端也跳过证书验证）
> 运行发现不行。
> 最后手动添加上 "cert": {两个证书路径
> 则运行成功。
> 建议提示一下反代一定要"cert": {

是否可以看下您的配置文件能发一下 观察一下吗？
