### ISSUE TITLE
对接v2b开tls没网

### ISSUE THREAD

**Issue by Mtoly** [crossfw/Air-Universe#3]
如标题
我对接v2b
后端这里成功申请了ssl证书
前端开tls后就没网了是咋回事

**Comment by Jerry-Zheng-bilibili** [comment]
前端有一个证书路径的你看看是不是和你后端上的是不是一样的，然后Allow Insecure这个是不是开着，如果开着就关了

**Comment by Mtoly** [comment]
一致，依然无网，
链接节点的话除非安卓客户端这里打开允许不安全不然就没有网

**Comment by Jerry-Zheng-bilibili** [comment]
那你这个就在面板端开启允许不安全开起来也就是Allow Insecure

**Comment by crossfw** [comment]
@Mtoly 你可能需要重新给证书目录读权限，这里的确有点问题

**Comment by Mtoly** [comment]
> @Mtoly 你可能需要重新给证书目录读权限，这里的确有点问题

我看看

**Comment by Mtoly** [comment]
> @Mtoly 你可能需要重新给证书目录读权限，这里的确有点问题

你好，我在重新给/root/.acme.sh/,/root/.cert/ 以及其中的子目录递归777权限后重新启动后端，仍然出现节点没有网络的问题，关闭tls有网

**Comment by crossfw** [comment]
忘了说明，证书在这里
```
CertPath: "/usr/local/share/au/server.crt",
KeyPath:  "/usr/local/share/au/server.key",
```

**Comment by Mtoly** [comment]
> 忘了说明，证书在这里
> 
> ```
> CertPath: "/usr/local/share/au/server.crt",
> KeyPath:  "/usr/local/share/au/server.key",
> ```
尝试重新获取证书后，给予证书目录777权限，重启后端。二次确认前端面板server name填写正确开启tls无网依然无法解决
