### ISSUE TITLE
关于in_tags 参数写法问题?

### ISSUE THREAD

**Issue by jinwyp** [crossfw/Air-Universe#30]
in_tags 具体的意思没看懂

使用官方安装脚本安装后

xray的配置 inbounds 的tag 是 "api"
"tag": "api"

而 au的配置 安装后默认是
https://github.com/crossfw/Air-Universe/blob/master/configs/Air-Universe_json/Air-Universe_full.json

那么值应该写成 p0 还是 api
"in_tags": [
      "api",
    ],   
还是写成    "in_tags": [
      "p0"
    ],

是需要写成和xray inbounds 的tag 的名称值一样的 "api"  还是直接用p0 , p1 这样代号 就行程序直接对应

**Comment by crossfw** [comment]
https://xtls.github.io/config/base/api/

后者，api是用来通信的

**Comment by jinwyp** [comment]
> https://xtls.github.io/config/base/api/
> 
> 后者，api是用来通信的

就是写成p0 ,p1这种 ? 
意思 对应是 xray inbounds的数组的第几个服务 对不对?

**Comment by crossfw** [comment]
> > https://xtls.github.io/config/base/api/
> > 后者，api是用来通信的
> 
> 就是写成p0 ,p1这种 ?
> 意思 对应是 xray inbounds的数组的第几个服务 对不对?

可自行决定

**Comment by jinwyp** [comment]
> > > https://xtls.github.io/config/base/api/
> > > 后者，api是用来通信的
> > 
> > 
> > 就是写成p0 ,p1这种 ?
> > 意思 对应是 xray inbounds的数组的第几个服务 对不对?
> 
> 可自行决定

没看懂 
1 是不是应该写成 p0, p1 这种
2 如果不是写成p0, p1 还可以写成什么?

**Comment by crossfw** [comment]
随便写，反正是自己设置的，默认就是p0开始递增【不写也可以】

**Comment by jinwyp** [comment]
> 随便写，反正是自己设置的，默认就是p0开始递增【不写也可以】

还是没看懂 随便写是什么意思?  需要和xray 配置的tag名称相同吗?

**Comment by crossfw** [comment]
看文档，是xray inbound的 tag

**Comment by crossfw** [comment]
> > 随便写，反正是自己设置的，默认就是p0开始递增【不写也可以】
> 
> 还是没看懂 随便写是什么意思? 需要和xray 配置的tag名称相同吗?
> 
> 最好能举个例子 到底怎么写 , 因为这个配置会导致启动失败
> in_tags 的作用是做什么的? 目前我只知道需要和 node_ids 的数组个数相同, 但具体做什么? 怎么写 完全不明白, p0,p1感觉就是个占位符, 难道写成1,2 也可以吗?

如果您使用自动配置入站且无路由配置需求请忽视这个配置选项，程序会自动运行

**Comment by jinwyp** [comment]
> 看文档，是xray inbound的 tag

顶楼写的例子 官方脚本安装后  xray的配置
```
 26   "inbounds": [
 27     {
 28       "listen": "127.0.0.1",
 29       "port": 10085,
 30       "protocol": "dokodemo-door",
 31       "settings": {
 32         "address": "127.0.0.1"
 33       },
 34       "tag": "api"
 35     }
 36   ],


```

那么 in_tags 如果写配置的话, 到底是写成 "p0" 还是 "api"

是写成
"in_tags": [
"api",
],

还是写成 "in_tags": [
"p0"
],


感觉应该写成 "in_tags": [
"api",
], 才对吧?

**Comment by crossfw** [comment]
```
"in_tags": [
"p0"
]
```
这样

**Comment by jinwyp** [comment]
> ```
> "in_tags": [
> "p0"
> ]
> ```
> 
> 这样

说明 p0 p1 只是个占位符 标识, 用来说明第几个位置 对吧?  和xray 的inbounds的 tag 名称值无关对吧?

**Comment by crossfw** [comment]
> > ```
> > "in_tags": [
> > "p0"
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样
> 
> 说明 p0 p1 只是个占位符 标识, 用来说明第几个位置 对吧? 和xray 的inbounds的 tag 名称值无关对吧?

我已经无法回答您的问题了，和xray的tag是对应的。。。

**Comment by jinwyp** [comment]
> > > ```
> > > "in_tags": [
> > > "p0"
> > > ]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这样
> > 
> > 
> > 说明 p0 p1 只是个占位符 标识, 用来说明第几个位置 对吧? 和xray 的inbounds的 tag 名称值无关对吧?
> 
> 我已经无法回答您的问题了，和xray的tag是对应的。。。

难道是air universe 自动创建了一个xray的 inbound,  tag 为p0 ?

**Comment by crossfw** [comment]
是的

**Comment by MittWillson** [comment]
@crossfw Test

**Comment by BaileyZyp** [comment]
@jinwyp 建议去看看xray官方文档 写得很透彻
