### ISSUE TITLE
报错：rpc error: code = Unknown desc = not enough information for making a decision

### ISSUE THREAD

**Issue by duudukaka** [crossfw/Air-Universe#34]
错误日志：Failed to obtain users info - invalid character 'e' looking for beginning of value
面板 v2oard
节点 ss 父节点 服务ip与后端ip一致
启动au后日志一直显示Failed to remove inbound - rpc error: code = Unknown desc = not enough information for making a decision 
![捕获](https://user-images.githubusercontent.com/34993508/129780661-ba669703-909c-47b9-a0e2-aad9e83dcef9.JPG)

**Comment by duudukaka** [comment]
get访问域名/api/v1/server/ShadowsocksTidalab/user?node_id=1&token=123456464878&local_port=1
回应为空 ``` {"data":[]} ```

**Comment by duudukaka** [comment]
![捕获](https://user-images.githubusercontent.com/34993508/129785130-f27aea54-ff6a-415e-85aa-9a4c67b54d60.JPG)
![捕获1](https://user-images.githubusercontent.com/34993508/129785142-00bae674-e420-473c-be00-0cc691e0e3cd.JPG)
手动启动后的xray与au日志截图

**Comment by crossfw** [comment]
是否存在ss的合法用户？[需要有一个用户可以使用该节点]

**Comment by duudukaka** [comment]
> 是否存在ss的合法用户？[需要有一个用户可以使用该节点]
感谢解答，已经解决
