### ISSUE TITLE
配置文件在自定义cert文件位置时无效。

### ISSUE THREAD

**Issue by houpi** [crossfw/Air-Universe#35]
我使用一键脚本安装，并也是使用的一键脚本里的申请tls证书，但发现配置文件里并没有cert里有相关的配置。但又能正常使用正常扶墙，同时发现xray日志里报 transport/internet/tls: failed to parse key > open /usr/local/share/au/server.key: permission denied

然后我自己在au.json里参加了cert配置，不管我这个配置参加和证书文件地址正不正确，xray日志依然报上述错误。但也能正常扶墙。请作者关注。

**Comment by houpi** [comment]
附xray配置文件
{
  "log": {
    "access": "/var/log/au/xr.log"
  },
  "stats": {},
  "api": {
    "services": [
      "HandlerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "policy": {
    "levels": {
      "0": {
        "handshake": 4,
        "connIdle": 60,
        "uplinkOnly": 2,
        "downlinkOnly": 5,
        "bufferSize": 0,
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    }
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10085,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blackhole",
      "protocol": "blackhole",
      "settings": {}
    },
    {
      "tag":"warp",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
           "address": "127.0.0.1",
           "port": 40000
          }
        ]
      }
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "type": "field",
        "protocol": [
          "bittorrent"
        ],
        "outboundTag": "blackhole"
      },
      {
        "type": "field",
        "ip": [
          "127.0.0.1/32",
          "10.0.0.0/8",
          "fc00::/7",
          "fe80::/10",
          "172.16.0.0/12"
        ],
        "outboundTag": "blackhole"
      },
      {
        "type": "field",
        "domain": [
          "geosite:private",
          "geosite:cn"
        ],
        "outboundTag": "blackhole"
      },
      {
        "type": "field",
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "blackhole"
      },
      {
        "type": "field",
        "domain": [
          "domain:hulu.com",        
          "domain:hulu.tv",
          "domain:huluim.com",
          "domain:hulustream.com",
          "full:cws-hulu.conviva.com",
          "full:assetshuluimcom-a.akamaihd.net",
          "domain:hbo.com",
          "domain:hbogo.com",
          "domain:hbonow.com",
          "domain:hbomax.com",
          "domain:hbomaxcdn.com",
          "geosite:youtube"                
        ],
        "outboundTag": "warp"
      }
    ]
  }
}

**Comment by houpi** [comment]
更新：cert自定义路径无效，只会找/usr/local/share/au/server.key这个默认路径证书

**Comment by crossfw** [comment]
给权限了吗

**Comment by houpi** [comment]
确定指定cert目录和文件是有权限的，而且日志里根本不报这个目录，只报
Failed to add inbound - infra/conf: failed to parse certificate > open /usr/local/share/au/server.crt: no such file or directory

除非我把指定目录里的文件拷贝并重命名到/usr/local/share/au/server.crt和key才能正常运行

**Comment by houpi** [comment]
{
  "panel": {
    "type": "v2board",
    "url": "https://ga.ga",
    "key": "gagaga",
    "node_ids": [21],
    "nodes_type": ["trojan"]
	}
  },
  "proxy": {
    "type":"xray",
    "cert": {
      "cert_path": "/etc/config/air-u/ga.ga/fullchain.pem",
      "key_path": "/etc/config/air-u/ga.ga/privkey.pem"
	}
  }
}

**Comment by crossfw** [comment]
> {
> "panel": {
> "type": "v2board",
> "url": "https://ga.ga",
> "key": "gagaga",
> "node_ids": [21],
> "nodes_type": ["trojan"]
> }
> },
> "proxy": {
> "type":"xray",
> "cert": {
> "cert_path": "/etc/config/air-u/ga.ga/fullchain.pem",
> "key_path": "/etc/config/air-u/ga.ga/privkey.pem"
> }
> }
> }

这格式不太对把，指json

**Comment by crossfw** [comment]
```
{
   "panel":{
      "type":"v2board",
      "url":"https://ga.ga",
      "key":"gagaga",
      "node_ids":[
         21
      ],
      "nodes_type":[
         "trojan"
      ]
   },
   "proxy":{
      "type":"xray",
      "cert":{
         "cert_path":"/etc/config/air-u/ga.ga/fullchain.pem",
         "key_path":"/etc/config/air-u/ga.ga/privkey.pem"
      }
   }
}
```
这是正确格式

**Comment by houpi** [comment]
运行起来了~
