### ISSUE TITLE
failed to receive server preface within timeout

### ISSUE THREAD

**Issue by TNED** [crossfw/Air-Universe#5]
![image](https://user-images.githubusercontent.com/19992111/155936631-73aa1b2e-ace8-4b68-9c5f-b0016609eb36.png)

**Comment by TNED** [comment]
这个错误是否会影响正常的使用。 我应该如何检查这个错误的具体原因。 
uname -a 执行后的结果
Linux instance-20220213-0845 5.4.17-2136.302.7.2.3.el8uek.aarch64 #2 SMP Tue Feb 8 11:24:19 PST 2022 aarch64 aarch64 aarch64 GNU/Linux

**Comment by Jerry-Zheng-bilibili** [comment]
你所对接的面板是哪一种

**Comment by TNED** [comment]
> 你所对接的面板是哪一种

v2board 这个

**Comment by Jerry-Zheng-bilibili** [comment]
Oracle的arm的机器是吧

**Comment by TNED** [comment]
这个是xray的配置：
`{
  "log": {
    "access": "/opt/xray/log/xr.log"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 40001,
      "protocol": "vmess",
      "settings": {
      },
      "tag": "api"
    }
  ]
}`
这个 au的配置
`{
  "panel": {
    "type": "v2board",
    "url": "-",
    "key": "-",
    "node_ids": [1],
    "nodes_type": ["vmess"]
  },
  "proxy": {
    "type":"xray",
    "api_port": 40001
  },
  "sync": {
    "interval": 60,
    "fail_delay": 5,
    "timeout": 5,
    "post_ip_interval": 90
  }
}`
版本都是下载的最新版

**Comment by TNED** [comment]
对的

**Comment by TNED** [comment]
> 对的



> Oracle的arm的机器是吧

对的

**Comment by TNED** [comment]
> Oracle的arm的机器是吧

需要测试的，我可以把地址和账户密码和密钥私发给你。

**Comment by Bend-Function** [comment]
你api inbound没配吗，请拆卸重装使用默认配置

**Comment by Jerry-Zheng-bilibili** [comment]
> > Oracle的arm的机器是吧
> 
> 需要测试的，我可以把地址和账户密码和密钥私发给你。

请使用默认配置，无须手动

**Comment by TNED** [comment]
> > > Oracle的arm的机器是吧
> > 
> > 
> > 需要测试的，我可以把地址和账户密码和密钥私发给你。
> 
> 请使用默认配置，无须手动

好的，我执行一下一键安装脚本，然后把配置文件同步一下。
如果没有问题我会主动关闭这个Issues.

**Comment by Jerry-Zheng-bilibili** [comment]
用一键脚本测试，没有复现你这个问题，你可以直接用一键脚本，按步骤一步一步配置

**Comment by crossfw** [comment]
> 这个是xray的配置： `{ "log": { "access": "/opt/xray/log/xr.log" }, "inbounds": [ { "listen": "127.0.0.1", "port": 40001, "protocol": "vmess", "settings": { }, "tag": "api" } ] }` 这个 au的配置 `{ "panel": { "type": "v2board", "url": "-", "key": "-", "node_ids": [1], "nodes_type": ["vmess"] }, "proxy": { "type":"xray", "api_port": 40001 }, "sync": { "interval": 60, "fail_delay": 5, "timeout": 5, "post_ip_interval": 90 } }` 版本都是下载的最新版

Xray配置文件缺失api inbound和相应route，如无特殊需求请不要动配置文件

**Comment by TNED** [comment]
> > 这个是xray的配置： `{ "log": { "access": "/opt/xray/log/xr.log" }, "inbounds": [ { "listen": "127.0.0.1", "port": 40001, "protocol": "vmess", "settings": { }, "tag": "api" } ] }` 这个 au的配置 `{ "panel": { "type": "v2board", "url": "-", "key": "-", "node_ids": [1], "nodes_type": ["vmess"] }, "proxy": { "type":"xray", "api_port": 40001 }, "sync": { "interval": 60, "fail_delay": 5, "timeout": 5, "post_ip_interval": 90 } }` 版本都是下载的最新版
> 
> Xray配置文件缺失api inbound和相应route，如无特殊需求请不要动配置文件



> 用一键脚本测试，没有复现你这个问题，你可以直接用一键脚本，按步骤一步一步配置

已经使用了一键脚本，却出现了另外的一个问题。 
`WARN[0005] NodeID: 1 IDIndex 0 - Failed to add inbound - rpc error: code = Unavailable desc = error reading from server: EOF.`
同时xray-core发生了panic
```
panic: Calling Domain() on an IPv4Address.

goroutine 26 [running]:
github.com/xtls/xray-core/common/net.ipv4Address.Domain(...)
	github.com/xtls/xray-core/common/net/address.go:132
github.com/xtls/xray-core/transport/internet/tcp.ListenTCP({0xba2fd0, 0x40000400b0}, {0xba4348, 0x400023e620}, 0x0, 0x400007e460, 0x400026f3f0)
	github.com/xtls/xray-core/transport/internet/tcp/hub.go:49 +0x13c
github.com/xtls/xray-core/transport/internet.ListenTCP({0xba2fd0, 0x40000400b0}, {0xba4348, 0x400023e620}, 0x0, 0x400007e460, 0x400026f3f0)
	github.com/xtls/xray-core/transport/internet/tcp_hub.go:73 +0x298
github.com/xtls/xray-core/app/proxyman/inbound.(*tcpWorker).Start(0x4000263220)
	github.com/xtls/xray-core/app/proxyman/inbound/worker.go:122 +0xb4
github.com/xtls/xray-core/app/proxyman/inbound.(*AlwaysOnInboundHandler).Start(0x40002055c0)
	github.com/xtls/xray-core/app/proxyman/inbound/always.go:156 +0x78
github.com/xtls/xray-core/app/proxyman/inbound.(*Manager).AddHandler(0x4000205300, {0xba3040, 0x4000264900}, {0xba34a0, 0x40002055c0})
	github.com/xtls/xray-core/app/proxyman/inbound/inbound.go:54 +0x334
github.com/xtls/xray-core/core.AddInboundHandler(0x40002594f0, 0x4000259180)
	github.com/xtls/xray-core/core/xray.go:109 +0xe0
github.com/xtls/xray-core/app/proxyman/command.(*handlerServer).AddInbound(0x4000265a10, {0xba3040, 0x40002650e0}, 0x4000265140)
	github.com/xtls/xray-core/app/proxyman/command/command.go:72 +0x38
github.com/xtls/xray-core/app/proxyman/command._HandlerService_AddInbound_Handler({0x9b83e0, 0x4000265a10}, {0xba3040, 0x40002650e0}, 0x40002772c0, 0x0)
	github.com/xtls/xray-core/app/proxyman/command/command_grpc.pb.go:145 +0x1bc
google.golang.org/grpc.(*Server).processUnaryRPC(0x40001b8e00, {0xbb1c68, 0x4000001520}, 0x40001fa480, 0x4000265b30, 0x11bf1a0, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1282 +0xc3c
google.golang.org/grpc.(*Server).handleStream(0x40001b8e00, {0xbb1c68, 0x4000001520}, 0x40001fa480, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1616 +0xa54
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x400023e310, 0x40001b8e00, {0xbb1c68, 0x4000001520}, 0x40001fa480)
	google.golang.org/grpc@v1.44.0/server.go:921 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.44.0/server.go:919 +0x1f0
```
 我想这个异常应该是我的v2board面板配置问题，我提供一下相关的配置参数。
`{"log":{"loglevel":"debug","access":"access.log","error":"error.log"},"api":{"services":["HandlerService","StatsService"],"tag":"api"},"dns":{},"stats":{},"inbounds":[{"port":40001,"protocol":"vmess","settings":{"clients":[]},"sniffing":{"enabled":false,"destOverride":["http","tls"]},"streamSettings":{"network":"ws"},"tag":"proxy"},{"listen":"127.0.0.1","port":1,"protocol":"dokodemo-door","settings":{"address":"0.0.0.0"},"tag":"api"}],"outbounds":[{"protocol":"freedom","settings":{}},{"protocol":"blackhole","settings":{},"tag":"block"}],"routing":{"rules":[{"type":"field","inboundTag":"api","outboundTag":"api"}]},"policy":{"levels":{"0":{"handshake":4,"connIdle":300,"uplinkOnly":5,"downlinkOnly":30,"statsUserUplink":true,"statsUserDownlink":true}}}}`

我无法确认异常具体产生的原因。

谢谢你们的帮助。

**Comment by fkx4-p** [comment]
> > > 这个是xray的配置： `{ "log": { "access": "/opt/xray/log/xr.log" }, "inbounds": [ { "listen": "127.0.0.1", "port": 40001, "protocol": "vmess", "settings": { }, "tag": "api" } ] }` 这个 au的配置 `{ "panel": { "type": "v2board", "url": "-", "key": "-", "node_ids": [1], "nodes_type": ["vmess"] }, "proxy": { "type":"xray", "api_port": 40001 }, "sync": { "interval": 60, "fail_delay": 5, "timeout": 5, "post_ip_interval": 90 } }` 版本都是下载的最新版
> > 
> > 
> > Xray配置文件缺失api inbound和相应route，如无特殊需求请不要动配置文件
> 
> > 用一键脚本测试，没有复现你这个问题，你可以直接用一键脚本，按步骤一步一步配置
> 
> 已经使用了一键脚本，却出现了另外的一个问题。 `WARN[0005] NodeID: 1 IDIndex 0 - Failed to add inbound - rpc error: code = Unavailable desc = error reading from server: EOF.` 同时xray-core发生了panic
> 
> ```
> panic: Calling Domain() on an IPv4Address.
> 
> goroutine 26 [running]:
> github.com/xtls/xray-core/common/net.ipv4Address.Domain(...)
> 	github.com/xtls/xray-core/common/net/address.go:132
> github.com/xtls/xray-core/transport/internet/tcp.ListenTCP({0xba2fd0, 0x40000400b0}, {0xba4348, 0x400023e620}, 0x0, 0x400007e460, 0x400026f3f0)
> 	github.com/xtls/xray-core/transport/internet/tcp/hub.go:49 +0x13c
> github.com/xtls/xray-core/transport/internet.ListenTCP({0xba2fd0, 0x40000400b0}, {0xba4348, 0x400023e620}, 0x0, 0x400007e460, 0x400026f3f0)
> 	github.com/xtls/xray-core/transport/internet/tcp_hub.go:73 +0x298
> github.com/xtls/xray-core/app/proxyman/inbound.(*tcpWorker).Start(0x4000263220)
> 	github.com/xtls/xray-core/app/proxyman/inbound/worker.go:122 +0xb4
> github.com/xtls/xray-core/app/proxyman/inbound.(*AlwaysOnInboundHandler).Start(0x40002055c0)
> 	github.com/xtls/xray-core/app/proxyman/inbound/always.go:156 +0x78
> github.com/xtls/xray-core/app/proxyman/inbound.(*Manager).AddHandler(0x4000205300, {0xba3040, 0x4000264900}, {0xba34a0, 0x40002055c0})
> 	github.com/xtls/xray-core/app/proxyman/inbound/inbound.go:54 +0x334
> github.com/xtls/xray-core/core.AddInboundHandler(0x40002594f0, 0x4000259180)
> 	github.com/xtls/xray-core/core/xray.go:109 +0xe0
> github.com/xtls/xray-core/app/proxyman/command.(*handlerServer).AddInbound(0x4000265a10, {0xba3040, 0x40002650e0}, 0x4000265140)
> 	github.com/xtls/xray-core/app/proxyman/command/command.go:72 +0x38
> github.com/xtls/xray-core/app/proxyman/command._HandlerService_AddInbound_Handler({0x9b83e0, 0x4000265a10}, {0xba3040, 0x40002650e0}, 0x40002772c0, 0x0)
> 	github.com/xtls/xray-core/app/proxyman/command/command_grpc.pb.go:145 +0x1bc
> google.golang.org/grpc.(*Server).processUnaryRPC(0x40001b8e00, {0xbb1c68, 0x4000001520}, 0x40001fa480, 0x4000265b30, 0x11bf1a0, 0x0)
> 	google.golang.org/grpc@v1.44.0/server.go:1282 +0xc3c
> google.golang.org/grpc.(*Server).handleStream(0x40001b8e00, {0xbb1c68, 0x4000001520}, 0x40001fa480, 0x0)
> 	google.golang.org/grpc@v1.44.0/server.go:1616 +0xa54
> google.golang.org/grpc.(*Server).serveStreams.func1.2(0x400023e310, 0x40001b8e00, {0xbb1c68, 0x4000001520}, 0x40001fa480)
> 	google.golang.org/grpc@v1.44.0/server.go:921 +0x94
> created by google.golang.org/grpc.(*Server).serveStreams.func1
> 	google.golang.org/grpc@v1.44.0/server.go:919 +0x1f0
> ```
> 
> 我想这个异常应该是我的v2board面板配置问题，我提供一下相关的配置参数。 `{"log":{"loglevel":"debug","access":"access.log","error":"error.log"},"api":{"services":["HandlerService","StatsService"],"tag":"api"},"dns":{},"stats":{},"inbounds":[{"port":40001,"protocol":"vmess","settings":{"clients":[]},"sniffing":{"enabled":false,"destOverride":["http","tls"]},"streamSettings":{"network":"ws"},"tag":"proxy"},{"listen":"127.0.0.1","port":1,"protocol":"dokodemo-door","settings":{"address":"0.0.0.0"},"tag":"api"}],"outbounds":[{"protocol":"freedom","settings":{}},{"protocol":"blackhole","settings":{},"tag":"block"}],"routing":{"rules":[{"type":"field","inboundTag":"api","outboundTag":"api"}]},"policy":{"levels":{"0":{"handshake":4,"connIdle":300,"uplinkOnly":5,"downlinkOnly":30,"statsUserUplink":true,"statsUserDownlink":true}}}}`
> 
> 我无法确认异常具体产生的原因。
> 
> 谢谢你们的帮助。

请问您解决了吗 我也遇到了相同问题
