### ISSUE TITLE
节点流量和在线人数似乎没有上报

### ISSUE THREAD

**Issue by Luciausa** [crossfw/Air-Universe#7]
节点流量和在线人数似乎没有上报
用到最新版v2ray，配置文件
config.json
```
{
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "stats": {"trackIp": false},
  "dns": {
    "servers": [
        "localhost"
    ]
  },
  "log": {
    "loglevel": "warning",
    "access": "/dev/null",
    "error": "/dev/null"
  },
  "inbounds": [
    {
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "listen": "0.0.0.0",
      "port": 10000,
      "protocol": "vmess",
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/xxxxxx"
        }
      },
      "tag": "id1"
    },
    {
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "listen": "0.0.0.0",
      "port": 10001,
      "protocol": "vmess",
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/xxxxxx2"
        }
      },
      "tag": "id2"
    },
    {
      "listen": "127.0.0.1",
      "port": 10085,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ]
      },
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      },
      {
        "type": "field",
        "ip": [
          "geoip:private",
          "255.255.255.255"
        ],
        "outboundTag": "blocked"
      }
    ],
    "strategy": "rules"
  }
}
```

Air-Universe.json
```
{
  "log": {
    "log_level": "info"
  },
  "panel": {
    "type": "sspanel",
    "url": "https://xxx.com",
    "key": "keykeykey",
    "node_ids": [1, 2]
  },
  "proxy": {
    "type": "v2ray",
    "alert_id": 2,
    "auto_generate": false,
    "in_tags": [
      "id1",
      "id2"
    ],
    "api_address": "127.0.0.1",
    "api_port": 10085,
    "log_path": "/dev/null",
    "speed_limit_level": [0, 0.1, 5, 10, 15]
  },
  "sync": {
    "interval": 60,
    "fail_delay": 5,
    "timeout": 5,
    "post_ip_interval": 300
  }
```

**Comment by crossfw** [comment]
在线人数统计基于 v2ray log 请指定log路径到一个真实的地址

我不是很清楚 stats 中的 trackIp 的意义，因为这里应该是空白的。
> "stats": {"trackIp": false}  -->  "stats": {}

更多细节请附上 Air-Universe 的 log

**Comment by NutterChen** [comment]
@crossfw log要存储？何不直接接管pipe直接提取数据？

**Comment by crossfw** [comment]
> @crossfw log要存储？何不直接接管pipe直接提取数据？

谢谢建议，有空试试看。

是指类似这样的命令吗
```shell
$ xray - c xray.json | au -c au.json
```

**Comment by NutterChen** [comment]
@crossfw 不是，在v2ray或xray中设置日志等级到最高，运行时它将实时输出访问日志

**Comment by NutterChen** [comment]
@crossfw 不过好像只有ip 没有显示用户(email)

**Comment by Luciausa** [comment]
从日志统计在线人数似乎不合理，有时候就是不想记录用户日志。记录日志还得定期清理，挺麻烦。
根据连接上来的 实时用户数用户数统计应该就可以吧，用户每次每次连接都要uuid认证，统计一定时间比如1分钟内认证过的uuid数就可以了吧

**Comment by crossfw** [comment]
> 从日志统计在线人数似乎不合理，有时候就是不想记录用户日志。记录日志还得定期清理，挺麻烦。
> 根据连接上来的 实时用户数用户数统计应该就可以吧，用户每次每次连接都要uuid认证，统计一定时间比如1分钟内认证过的uuid数就可以了吧

日志根据你自己设置的上报间隔清理，我不会修改代理内核，这样可以无需我自己更新以适配代理内核的最新功能，后期会使用上面那位大佬的方法试一试

**Comment by Luciausa** [comment]
Air-Universe的不参与用户认证吗，正常一个v2ray服务器节点配置一个固定的uuid。
那Air-Universe 只是面板的所有有效用户的uuid传递给v2ray core， 但是并不参与认证过程，是这样吗？

**Comment by crossfw** [comment]
> Air-Universe的不参与用户认证吗，正常一个v2ray服务器节点配置一个固定的uuid。
> 那Air-Universe 只是面板的所有有效用户的uuid传递给v2ray core， 但是并不参与认证过程，是这样吗？

是的

**Comment by Luciausa** [comment]
打开了v2ray的访问日志，记录到 /var/log/v2-access.log
然后，"log_path": "/var/log/v2-access.log",  这个也配置了
还是没有在线人数
我的/var/log/v2-access.log内容大致为
```
2021/03/15 19:16:03 127.0.0.1:38766 accepted tcp:www.gstatic.com:80 email: 5212-f21
2021/03/15 19:16:04 127.0.0.1:46948 accepted tcp:access-sngapm.qcloud.com:443 email: 3668-node2
2021/03/15 19:16:07 127.0.0.1:46950 accepted tcp:access-sngapm.qcloud.com:443 email: 3668-node2
2021/03/15 19:16:08 127.0.0.1:46952 accepted tcp:access-sngapm.qcloud.com:443 email: 3668-node2
2021/03/15 19:16:09 127.0.0.1:46954 accepted tcp:access-sngapm.qcloud.com:443 email: 3668-node2
2021/03/15 19:16:10 127.0.0.1:46958 accepted tcp:access-sngapm.qcloud.com:443 email: 3668-node2
2021/03/15 19:16:10 127.0.0.1:46956 accepted tcp:www.voachinese.com:443 email: 3668-node2
```
那至少应该有一个在线用户，但是在线用户一直显示0

**Comment by Luciausa** [comment]
Air-Universe 有输出日志 
WARN[1203] Failed to post alive IP - invalid character '<' looking for beginning of value 
WARN[1504] Failed to post alive IP - invalid character '<' looking for beginning of value 

alive IP 这个报错，可能是因为我的面板block的  alive IP 的上报，但是这个应该不影响上报用户数吧？

**Comment by Luciausa** [comment]
> > 从日志统计在线人数似乎不合理，有时候就是不想记录用户日志。记录日志还得定期清理，挺麻烦。
> > 根据连接上来的 实时用户数用户数统计应该就可以吧，用户每次每次连接都要uuid认证，统计一定时间比如1分钟内认证过的uuid数就可以了吧
> 
> 日志根据你自己设置的上报间隔清理，我不会修改代理内核，这样可以无需我自己更新以适配代理内核的最新功能，后期会使用上面那位大佬的方法试一试

我的上报间隔是默认设置：
  "sync": {
    "interval": 60,
但是访问日志 /var/log/v2-access.log  一直增长，并没有被定时清理。v2-access.log 这个文件的权限已经改成777了

**Comment by crossfw** [comment]
> Air-Universe 有输出日志
> WARN[1203] Failed to post alive IP - invalid character '<' looking for beginning of value
> WARN[1504] Failed to post alive IP - invalid character '<' looking for beginning of value
> 
> alive IP 这个报错，可能是因为我的面板block的 alive IP 的上报，但是这个应该不影响上报用户数吧？

请问在这之前出现过
>Failed to get alive IP 
错误吗

请 chmod -R 777 /var/log/ 尝试一下。

**Comment by Luciausa** [comment]
没有 Failed to get alive IP
```
WARN[1203] Failed to post alive IP - invalid character '<' looking for beginning of value 
WARN[1504] Failed to post alive IP - invalid character '<' looking for beginning of value 
WARN[1804] Failed to post alive IP - invalid character '<' looking for beginning of value 
INFO[2101] NodeID: 2 IDIndex 1 - Remove users num: 1   
INFO[2102] NodeID: 1 IDIndex 0 - Remove users num: 1   
WARN[2105] Failed to post alive IP - invalid character '<' looking for beginning of value 
WARN[2405] Failed to post alive IP - invalid character '<' looking for beginning of value 
WARN[2706] Failed to post alive IP - invalid character '<' looking for beginning of value 
INFO[2779] NodeID: 2 IDIndex 1 - Add users num: 1      
INFO[2780] NodeID: 1 IDIndex 0 - Add users num: 1      
WARN[3006] Failed to post alive IP - invalid character '<' looking for beginning of value 
WARN[3307] Failed to post alive IP - invalid character '<' looking for beginning of value 
WARN[3607] Failed to post alive IP - invalid character '<' looking for beginning of value 
WARN[3908] Failed to post alive IP - invalid character '<' looking for beginning of value 
```
 chmod -R 777 /var/log/  已做，好像也还不行

**Comment by Luciausa** [comment]
现在 v2-access.log有被定时清空了
但是 使用人数还没有

**Comment by Luciausa** [comment]
我观察没有按照 "sync": {
"interval": 60,
这个间隔清空日志
而是大约5分钟清空一次日志

**Comment by crossfw** [comment]
> 我观察没有按照 "sync": {
> "interval": 60,
> 这个间隔清空日志
> 而是大约5分钟清空一次日志

是的，默认300s清空，也可以在配置文件里修改
请把air universe日志等级调整为debug记录日志，我后续会持续关注这个问题

**Comment by Luciausa** [comment]
```
DEBU[0061] NodeID: 1 IDIndex 0 - Post Traffic data success - [] 
DEBU[0062] NodeID: 1 IDIndex 0 - Successfully post system load - {Uptime:79316 Load1:0.02 Load5:0.06 Load15:0.05} 
DEBU[0062] NodeID: 1 IDIndex 0 - Successfully obtain node info 
DEBU[0062] NodeID: 2 IDIndex 1 - Post Traffic data success - [] 
DEBU[0062] NodeID: 2 IDIndex 1 - Successfully post system load - {Uptime:79317 Load1:0.02 Load5:0.06 Load15:0.05} 
DEBU[0062] NodeID: 2 IDIndex 1 - Successfully obtain node info 
DEBU[0062] NodeID: 1 IDIndex 0 - Successfully obtain users info 
DEBU[0063] NodeID: 2 IDIndex 1 - Successfully obtain users info 
DEBU[0123] NodeID: 1 IDIndex 0 - Post Traffic data success - [] 
DEBU[0123] NodeID: 1 IDIndex 0 - Successfully post system load - {Uptime:79378 Load1:0.09 Load5:0.08 Load15:0.06} 
DEBU[0123] NodeID: 2 IDIndex 1 - Post Traffic data success - [] 
DEBU[0123] NodeID: 2 IDIndex 1 - Successfully post system load - {Uptime:79378 Load1:0.09 Load5:0.08 Load15:0.06} 
DEBU[0123] NodeID: 1 IDIndex 0 - Successfully obtain node info 
DEBU[0123] NodeID: 2 IDIndex 1 - Successfully obtain node info 
DEBU[0124] NodeID: 1 IDIndex 0 - Successfully obtain users info 
DEBU[0124] NodeID: 2 IDIndex 1 - Successfully obtain users info 
DEBU[0184] NodeID: 2 IDIndex 1 - Post Traffic data success - [] 
DEBU[0184] NodeID: 1 IDIndex 0 - Post Traffic data success - [] 
DEBU[0185] NodeID: 2 IDIndex 1 - Successfully post system load - {Uptime:79439 Load1:0.03 Load5:0.06 Load15:0.05} 
DEBU[0185] NodeID: 1 IDIndex 0 - Successfully post system load - {Uptime:79439 Load1:0.03 Load5:0.06 Load15:0.05} 
DEBU[0185] NodeID: 1 IDIndex 0 - Successfully obtain node info 
DEBU[0185] NodeID: 2 IDIndex 1 - Successfully obtain node info 
DEBU[0185] NodeID: 1 IDIndex 0 - Successfully obtain users info 
DEBU[0185] NodeID: 2 IDIndex 1 - Successfully obtain users info 
DEBU[0246] NodeID: 1 IDIndex 0 - Post Traffic data success - [] 
DEBU[0246] NodeID: 2 IDIndex 1 - Post Traffic data success - [] 
DEBU[0246] NodeID: 2 IDIndex 1 - Successfully post system load - {Uptime:79501 Load1:0.04 Load5:0.06 Load15:0.05} 
DEBU[0246] NodeID: 1 IDIndex 0 - Successfully post system load - {Uptime:79501 Load1:0.04 Load5:0.06 Load15:0.05} 
DEBU[0247] NodeID: 1 IDIndex 0 - Successfully obtain node info 
DEBU[0247] NodeID: 2 IDIndex 1 - Successfully obtain node info 
DEBU[0247] NodeID: 2 IDIndex 1 - Successfully obtain users info 
DEBU[0247] NodeID: 1 IDIndex 0 - Successfully obtain users info 
DEBU[0302] Alive IP data [{Id:1688 InTag:n1 AliveIP:[127.0.0.1]} {Id:4923 InTag:n2 AliveIP:[127.0.0.1]} {Id:5771 InTag:n2 AliveIP:[127.0.0.1]} {Id:3650 InTag:n2 AliveIP:[127.0.0.1]} {Id:1 InTag:n2 AliveIP:[127.0.0.1]} {Id:4763 InTag:n2 AliveIP:[127.0.0.1]} {Id:825 InTag:n2 AliveIP:[127.0.0.1]} {Id:4899 InTag:n2 AliveIP:[127.0.0.1]} {Id:4899 InTag:n1 AliveIP:[127.0.0.1]} {Id:5212 InTag:n1 AliveIP:[127.0.0.1]} {Id:246 InTag:n2 AliveIP:[127.0.0.1]} {Id:4281 InTag:n1 AliveIP:[127.0.0.1]} {Id:4281 InTag:n2 AliveIP:[127.0.0.1]} {Id:4995 InTag:n1 AliveIP:[127.0.0.1]} {Id:5746 InTag:n1 AliveIP:[127.0.0.1]} {Id:2261 InTag:n2 AliveIP:[127.0.0.1]} {Id:2261 InTag:n1 AliveIP:[127.0.0.1]} {Id:1688 InTag:n2 AliveIP:[127.0.0.1]} {Id:2571 InTag:n1 AliveIP:[127.0.0.1]}] 
WARN[0302] Failed to post alive IP - invalid character '<' looking for beginning of value 
DEBU[0308] NodeID: 2 IDIndex 1 - Post Traffic data success - [] 
DEBU[0308] NodeID: 1 IDIndex 0 - Post Traffic data success - [] 
DEBU[0308] NodeID: 2 IDIndex 1 - Successfully post system load - {Uptime:79563 Load1:0.09 Load5:0.06 Load15:0.05} 
DEBU[0308] NodeID: 1 IDIndex 0 - Successfully post system load - {Uptime:79563 Load1:0.09 Load5:0.06 Load15:0.05} 
DEBU[0308] NodeID: 2 IDIndex 1 - Successfully obtain node info 
DEBU[0308] NodeID: 1 IDIndex 0 - Successfully obtain node info 
DEBU[0309] NodeID: 2 IDIndex 1 - Successfully obtain users info 
INFO[0309] NodeID: 2 IDIndex 1 - Remove users num: 1   
DEBU[0309] NodeID: 1 IDIndex 0 - Successfully obtain users info 
INFO[0309] NodeID: 1 IDIndex 0 - Remove users num: 1   
```

**Comment by crossfw** [comment]
> ```
> DEBU[0061] NodeID: 1 IDIndex 0 - Post Traffic data success - [] 
> DEBU[0062] NodeID: 1 IDIndex 0 - Successfully post system load - {Uptime:79316 Load1:0.02 Load5:0.06 Load15:0.05} 
> DEBU[0062] NodeID: 1 IDIndex 0 - Successfully obtain node info 
> DEBU[0062] NodeID: 2 IDIndex 1 - Post Traffic data success - [] 
> DEBU[0062] NodeID: 2 IDIndex 1 - Successfully post system load - {Uptime:79317 Load1:0.02 Load5:0.06 Load15:0.05} 
> DEBU[0062] NodeID: 2 IDIndex 1 - Successfully obtain node info 
> DEBU[0062] NodeID: 1 IDIndex 0 - Successfully obtain users info 
> DEBU[0063] NodeID: 2 IDIndex 1 - Successfully obtain users info 
> DEBU[0123] NodeID: 1 IDIndex 0 - Post Traffic data success - [] 
> DEBU[0123] NodeID: 1 IDIndex 0 - Successfully post system load - {Uptime:79378 Load1:0.09 Load5:0.08 Load15:0.06} 
> DEBU[0123] NodeID: 2 IDIndex 1 - Post Traffic data success - [] 
> DEBU[0123] NodeID: 2 IDIndex 1 - Successfully post system load - {Uptime:79378 Load1:0.09 Load5:0.08 Load15:0.06} 
> DEBU[0123] NodeID: 1 IDIndex 0 - Successfully obtain node info 
> DEBU[0123] NodeID: 2 IDIndex 1 - Successfully obtain node info 
> DEBU[0124] NodeID: 1 IDIndex 0 - Successfully obtain users info 
> DEBU[0124] NodeID: 2 IDIndex 1 - Successfully obtain users info 
> DEBU[0184] NodeID: 2 IDIndex 1 - Post Traffic data success - [] 
> DEBU[0184] NodeID: 1 IDIndex 0 - Post Traffic data success - [] 
> DEBU[0185] NodeID: 2 IDIndex 1 - Successfully post system load - {Uptime:79439 Load1:0.03 Load5:0.06 Load15:0.05} 
> DEBU[0185] NodeID: 1 IDIndex 0 - Successfully post system load - {Uptime:79439 Load1:0.03 Load5:0.06 Load15:0.05} 
> DEBU[0185] NodeID: 1 IDIndex 0 - Successfully obtain node info 
> DEBU[0185] NodeID: 2 IDIndex 1 - Successfully obtain node info 
> DEBU[0185] NodeID: 1 IDIndex 0 - Successfully obtain users info 
> DEBU[0185] NodeID: 2 IDIndex 1 - Successfully obtain users info 
> DEBU[0246] NodeID: 1 IDIndex 0 - Post Traffic data success - [] 
> DEBU[0246] NodeID: 2 IDIndex 1 - Post Traffic data success - [] 
> DEBU[0246] NodeID: 2 IDIndex 1 - Successfully post system load - {Uptime:79501 Load1:0.04 Load5:0.06 Load15:0.05} 
> DEBU[0246] NodeID: 1 IDIndex 0 - Successfully post system load - {Uptime:79501 Load1:0.04 Load5:0.06 Load15:0.05} 
> DEBU[0247] NodeID: 1 IDIndex 0 - Successfully obtain node info 
> DEBU[0247] NodeID: 2 IDIndex 1 - Successfully obtain node info 
> DEBU[0247] NodeID: 2 IDIndex 1 - Successfully obtain users info 
> DEBU[0247] NodeID: 1 IDIndex 0 - Successfully obtain users info 
> DEBU[0302] Alive IP data [{Id:1688 InTag:n1 AliveIP:[127.0.0.1]} {Id:4923 InTag:n2 AliveIP:[127.0.0.1]} {Id:5771 InTag:n2 AliveIP:[127.0.0.1]} {Id:3650 InTag:n2 AliveIP:[127.0.0.1]} {Id:1 InTag:n2 AliveIP:[127.0.0.1]} {Id:4763 InTag:n2 AliveIP:[127.0.0.1]} {Id:825 InTag:n2 AliveIP:[127.0.0.1]} {Id:4899 InTag:n2 AliveIP:[127.0.0.1]} {Id:4899 InTag:n1 AliveIP:[127.0.0.1]} {Id:5212 InTag:n1 AliveIP:[127.0.0.1]} {Id:246 InTag:n2 AliveIP:[127.0.0.1]} {Id:4281 InTag:n1 AliveIP:[127.0.0.1]} {Id:4281 InTag:n2 AliveIP:[127.0.0.1]} {Id:4995 InTag:n1 AliveIP:[127.0.0.1]} {Id:5746 InTag:n1 AliveIP:[127.0.0.1]} {Id:2261 InTag:n2 AliveIP:[127.0.0.1]} {Id:2261 InTag:n1 AliveIP:[127.0.0.1]} {Id:1688 InTag:n2 AliveIP:[127.0.0.1]} {Id:2571 InTag:n1 AliveIP:[127.0.0.1]}] 
> WARN[0302] Failed to post alive IP - invalid character '<' looking for beginning of value 
> DEBU[0308] NodeID: 2 IDIndex 1 - Post Traffic data success - [] 
> DEBU[0308] NodeID: 1 IDIndex 0 - Post Traffic data success - [] 
> DEBU[0308] NodeID: 2 IDIndex 1 - Successfully post system load - {Uptime:79563 Load1:0.09 Load5:0.06 Load15:0.05} 
> DEBU[0308] NodeID: 1 IDIndex 0 - Successfully post system load - {Uptime:79563 Load1:0.09 Load5:0.06 Load15:0.05} 
> DEBU[0308] NodeID: 2 IDIndex 1 - Successfully obtain node info 
> DEBU[0308] NodeID: 1 IDIndex 0 - Successfully obtain node info 
> DEBU[0309] NodeID: 2 IDIndex 1 - Successfully obtain users info 
> INFO[0309] NodeID: 2 IDIndex 1 - Remove users num: 1   
> DEBU[0309] NodeID: 1 IDIndex 0 - Successfully obtain users info 
> INFO[0309] NodeID: 1 IDIndex 0 - Remove users num: 1   
> ```

我明天会看一下的，应该是代码问题，感谢反馈

**Comment by crossfw** [comment]
请问现在还有流量不上报的问题吗

**Comment by Luciausa** [comment]
有，流量和在线用户数都不上报

**Comment by crossfw** [comment]
> 有，流量和在线用户数都不上报

你用的v2ray内核是什么版本的。
你流量不统计的原因是没有设置policy。请按照样例配置设置policy，设置level为0，
如果使用了非支持限速的v2ray内核，请删除 Air-universe 配置中的"speed_limit_level"

**Comment by Luciausa** [comment]
哪里有policy样例

**Comment by crossfw** [comment]
> 哪里有policy样例

https://github.com/crossfw/Air-Universe/blob/master/configs/v2ray-core_json/Single.json

只需要这样即可
```json
  "policy": {
    "levels": {
        "0": {
            "statsUserDownlink": true,
            "statsUserUplink": true
        }
    }
}
```

**Comment by Luciausa** [comment]
哦，非常感谢，流量和数据都有了。
开始看这个文档 
https://github.com/crossfw/Air-Universe/blob/master/docs/Install_cn.md
V2ray 的 样例地址  没有链接，所以没发现样例，自己随便写了一个。
非常感谢！！！

**Comment by crossfw** [comment]
@Luciausa ok，以后更新一波文档
