### ISSUE TITLE
启动报错  Failed to add users - rpc error: code 

### ISSUE THREAD

**Issue by Luciausa** [crossfw/Air-Universe#8]
2021/03/15 18:29:25 WARNING: proto: file "proxy/vmess/inbound/config.proto" is already registered
        previously from: "github.com/v2fly/v2ray-core/v4/proxy/vmess/inbound"
        currently from:  "github.com/xtls/xray-core/proxy/vmess/inbound"
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2021/03/15 18:29:25 WARNING: proto: file "proxy/vmess/outbound/config.proto" is already registered
        previously from: "github.com/v2fly/v2ray-core/v4/proxy/vmess/outbound"
        currently from:  "github.com/xtls/xray-core/proxy/vmess/outbound"
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2021/03/15 18:29:25 WARNING: proto: file "app/dispatcher/config.proto" is already registered
        previously from: "github.com/v2fly/v2ray-core/v4/app/dispatcher"
        currently from:  "github.com/xtls/xray-core/app/dispatcher"
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

INFO[0000] NodeID: 1 IDIndex 0 - Successfully start sync thread 
WARN[0000] NodeID: 1 IDIndex 0 - Failed to add users - rpc error: code = Unknown desc = github.com/v2fly/v2ray-core/v4/proxy/vmess/inbound: User 1-id1 already exists. 
INFO[0001] NodeID:2 IDIndex 1 - Successfully start sync thread 
WARN[0002] NodeID:2 IDIndex 1 - Failed to add users - rpc error: code = Unknown desc = github.com/v2fly/v2ray-core/v4/proxy/vmess/inbound: User 1-id2 already exists.

**Comment by crossfw** [comment]
确认你代理内核的tag是不同的，并且在启动时使用脚本或先启动代理再启动air universe
