### ISSUE TITLE
后端使用air最新加xray-core最新报错

### ISSUE THREAD

**Issue by fengguowudi** [crossfw/Air-Universe#8]
time="2022-03-26T20:58:01+08:00" level=warning msg="NodeID: 69 IDIndex 0 - Failed to add inbound - rpc error: code = Unavailable desc = error reading from server: EOF"
Mar 26 20:58:01 localhost systemd[1]: Stopping Air-Universe - main Service...
Mar 26 20:58:01 localhost

**Comment by fengguowudi** [comment]
使用协议 vmess ws

**Comment by crossfw** [comment]
fixed at v1.1.0
